config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  devise_for :users

  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :create] do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/friend-request', to: 'friendships#friend_request'
  post '/accept-request', to: 'friendships#accept_request'
  post '/reject-request', to: "friendships#reject_request"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { maximum: 200,
                                                too_long: '200 characters in comment is the maximum allowed.' }

  belongs_to :user
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  def confirm_friend
    update_attributes(confirmed: true)
    Friendship.create!(friend_id: user_id,
                       user_id: friend_id,
                       confirmed: true)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :post_id }

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: { maximum: 1000,
                                                too_long: '1000 characters in post is the maximum allowed.' }

  belongs_to :user

  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 20 }

  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :friendships
  has_many :confirmed_friendships, -> { where confirmed: true }, class_name: 'Friendship'
  has_many :friends, through: :confirmed_friendships

  has_many :pending_friendships, -> { where confirmed: nil }, class_name: 'Friendship', foreign_key: 'user_id'
  has_many :pending_friends, through: :pending_friendships, source: :friend

  has_many :inverse_friendships, -> { where confirmed: nil }, class_name: 'Friendship', foreign_key: 'friend_id'
  has_many :friend_requests, through: :inverse_friendships, source: :user

  def friend?(user)
    friends.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.user = current_user

    if @comment.save
      redirect_to posts_path, notice: 'Comment was successfully created.'
    else
      redirect_to posts_path, alert: @comment.errors.full_messages.join('. ').to_s
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!

  def friend_request
    current_user.friendships.create!(friendship_params)
    if current_user.save
      redirect_to current_user
    else
      redirect_to root_path
    end
  end

  def accept_request
    value = friendship_params[:friend_id]
    friend = User.find(value)
    friendship = friend.friendships.find_by(friend_id: current_user.id)
    if current_user.friend_requests.include?(friend)
      friendship.confirm_friend
      redirect_to current_user
    else
      redirect_to root_path
    end
  end

  def reject_request
    friendship = Friendship.find_by(friend_id: current_user.id)
    if friendship
      friendship.destroy
      redirect_to
    else
      redirect_to root_path
    end
  end

  private

  def friendship_params
    params.require(:friendship).permit(:friend_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new(post_id: params[:post_id])

    if @like.save
      redirect_to posts_path, notice: 'You liked a post.'
    else
      redirect_to posts_path, alert: 'You cannot like this post.'
    end
  end

  def destroy
    like = Like.find_by(id: params[:id], user: current_user, post_id: params[:post_id])
    if like
      like.destroy
      redirect_to posts_path, notice: 'You disliked a post.'
    else
      redirect_to posts_path, alert: 'You cannot dislike post that you did not like before.'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @post = Post.new
    timeline_posts
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      timeline_posts
      render :index, alert: 'Post was not created.'
    end
  end

  private

  def timeline_posts
    @timeline_posts ||= Post.all.ordered_by_most_recent.includes(:user)
  end

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @friendship = Friendship.new
    @users = User.all
  end

  def show
    @friendship = Friendship.new
    @user = User.find(params[:id])
    @posts = @user.posts.ordered_by_most_recent
  end

  private

  def mutual_friends(user)
    current_user.friends & user.friends
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_link_to(link_text, link_path)
    class_name = current_page?(link_path) ? 'menu-item active' : 'menu-item'

    content_tag(:div, class: class_name) do
      link_to link_text, link_path
    end
  end

  def like_or_dislike_btn(post)
    like = Like.find_by(post: post, user: current_user)
    if like
      link_to('Dislike!', post_like_path(id: like.id, post_id: post.id), method: :delete)
    else
      link_to('Like!', post_likes_path(post_id: post.id), method: :post)
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
  def mutual_friends(user)
    mutual = current_user.friends & user.friends
    return if mutual.empty?

    mutual.map(&:name).join(', ')
  end

  def relevant_post(post)
    if current_user.friends.include?(post.user) or post.user == current_user then true
    else false end
  end

  def friends?(user)
    if current_user.friend?(user)
      content_tag(:p, 'Already Friends!')
    elsif current_user.pending_friends.include?(user)
      content_tag(:p, 'Friend Request Pending')
    elsif current_user.friend_requests.include?(user)
      render partial: 'users/accept_request'
    else
      render partial: 'users/send_request'
    end
  end

  def incoming_requests
    unless current_user.friend_requests.empty?
      tag = content_tag(:h3, 'Friend requests: ')
      current_user.friend_requests.each do |request|
        tag += render partial: 'users/incoming_requests', locals: { request: request }
      end
    end
    tag
  end
end

app/helpers/post_helper.rb
module PostHelper
  def display_errors(post)
    return unless post.errors.full_messages.any?

    content_tag :p, "Post could not be saved. #{post.errors.full_messages.join('. ')}", class: 'errors'
  end
end

app/views/comments/_comment.html.erb
<div class="post-comments">
  <p>
    <b><%= comment.user.name %>:</b> <%= comment.content %>
  </p>
  <span> <%= comment.created_at.strftime("%Y/%m/%d") %> </span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorSocialScaffold</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="nav">
      <%= link_to 'Stay in touch', root_path %>
      <div class="menu">
        <div class="menu-item">
          <%= menu_link_to 'Timeline', posts_path %>
        </div>
        <div class="menu-item">
          <%= menu_link_to 'All users', users_path %>
        </div>
      </div>
      <% if current_user %>
        <%=link_to "#{current_user.name}", current_user%>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign in', user_session_path %>
      <% end %>
    </nav>
    <% if notice.present? %>
      <div class="notice">
        <p> <%= notice %> </p>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert">
        <p> <%= alert %> </p>
      </div>
    <% end %>
    <main class="main">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_post.html.erb
<% if relevant_post(post) %>
  <li class="post">
  <div>
    <div class='post-attribution' >
      <%= link_to post.user.name, user_path(post.user), class: 'post-author' %>
    </div>
    <div class='post-liking'>
      <span class='post-date'> <%= post.created_at.strftime("%Y/%m/%d") %> </span>
      <%= like_or_dislike_btn(post) %>
    </div>
  </div>
  <p class="post-content">
    <%= post.content %>
  </p>

  <div class='post-comments-section'>
    <%= render partial: 'comments/comment', collection: post.comments %>

    <%= form_for(post.comments.new, url: post_comments_path(post)) do |form| %>
      <%= form.text_field :content, id: :comment_content, class: 'form-control', placeholder: 'Add new Comment' %>
      <%= form.submit 'Comment', class: 'btn btn-secondary' %>
    <% end %>
  </div>
</li>

<% end %>

app/views/posts/index.html.erb
<%= form_for(@post) do |form| %>
  <%= form.label :content %>
  <%= form.text_field :content, id: :post_content, class: 'form-control', placeholder: 'Add New Post' %>
  <%= display_errors(@post) %>
  <%= form.submit 'Save', class: 'btn btn-primary' %>
<% end %>

<article class="timeline">
  <h3>
    Recent posts
  </h3>
  <ul class="posts">
    <%= render @timeline_posts %>
  </ul>
</article>

app/views/users/_accept_request.html.erb
<%= form_with model: @friendship, url: '/accept-request', method: :post do |form|%>
    <%= form.hidden_field :friend_id, value: "#{@user.id}" %>
    <div>
        <%= form.submit "Accept Request!"%>
    </div>
<% end %>
<%= form_with model: @friendship, url: '/reject-request', method: :post do |form|%>
    <%= form.hidden_field :friend_id, value: "#{@user.id}" %>
    <div>
        <%= form.submit "Reject Request!"%>
    </div>
<% end %>

app/views/users/_incoming_requests.html.erb
<li>
    <%=request.name %>
    <%= form_with model: @friendship, url: '/accept-request', method: :post do |form|%>
        <%= form.hidden_field :friend_id, value: "#{request.id}" %>
        <div>
        <%= form.submit "Accept Request!"%>
        </div>
    <% end %>
    <%= form_with model: @friendship, url: '/reject-request', method: :post do |form|%>
        <%= form.hidden_field :friend_id, value: "#{request.id}" %>
        <div>
        <%= form.submit "Reject Request!"%>
        </div>
    <% end %>
</li>

app/views/users/_send_request.html.erb
<%= form_with model: @friendship, url: '/friend-request', method: :post do |form|%>
    <% flash.each do |type, msg| %>
    <div>
        <h3><%= msg %></h3>
    </div>
    <% end %>
    <%= form.hidden_field :friend_id, value: "#{@user.id}" %>
    <div class="actions">
    <%= form.submit "Send Friend Request!"%>
    </div>
<% end %>

app/views/users/_user.html.erb
<li>
  Name: <%= user.name %>
  <span class="profile-link">
    <%= link_to 'See Profile',  user_path(user), class: 'profile-link' %>
      <% unless current_user == user %>
        <% unless current_user.friends.include?(user) %>
          <% unless current_user.pending_friends.include?(user) or current_user.friend_requests.include?(user)%>
            <%= form_with model: @friendship, url: '/friend-request', method: :post, class: "index-submit" do |form|%>
              <%= form.hidden_field :friend_id, value: "#{user.id}" %>
              <%= form.submit "Send Friend Request!"%>
            <% end %>
          <% end %>
      <% end %>
    <% end %>
  </span>

</li>

app/views/users/index.html.erb
<section class="users-section">
  <ul class="users-list">
    <%= render @users %>
  </ul>
</section>

app/views/users/show.html.erb
<section class="user-section">
  <h2><%= "Name: #{@user.name}" %></h2>
  <br>
  <% unless current_user == @user %>
    <% unless mutual_friends(@user).nil? %>
      <h3>Mutual friends: </h3>
      <%= mutual_friends(@user)%>
      <br>
    <% end %>
      
    <% if current_user.friend?(@user) %>
      <br>
      <p>Already Friends!</p>
    <% else %>
      <% if current_user.pending_friends.include?(@user) %>
        Friend Request Pending!
        <% elsif current_user.friend_requests.each do |request|%>
          <% if @user == request %>
            <%= form_with model: @friendship, url: '/accept-request', method: :post do |form|%>
                <%= form.hidden_field :friend_id, value: "#{request.id}" %>
                <div>
                <%= form.submit "Accept Request!"%>
              </div>
            <% end %>
            <%= form_with model: @friendship, url: '/reject-request', method: :post do |form|%>
              <%= form.hidden_field :friend_id, value: "#{request.id}" %>
              <div>
                <%= form.submit "Reject Request!"%>
              </div>
            <% end %>
          <% end %>
        <% end %>
      <% else %>
        <p>Send Friend Request</p>
        <%= form_with model: @friendship, url: '/friend-request', method: :post do |form|%>
          <% flash.each do |type, msg| %>
            <div>
              <h3><%= msg %></h3>
            </div>
            <% end %>
            <%= form.hidden_field :friend_id, value: "#{@user.id}" %>
            <div class="actions">
            <%= form.submit "Send Friend Request!"%>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% else %>
    <% unless current_user.friend_requests.empty? %>
      <h3>Friend Requests: </h3>
      <ul>
        <% current_user.friend_requests.each do |request|%>
        <li><%=request.name %>
            <%= form_with model: @friendship, url: '/accept-request', method: :post do |form|%>
                <%= form.hidden_field :friend_id, value: "#{request.id}" %>
                <div>
                <%= form.submit "Accept Request!"%>
              </div>
            <% end %>
            <%= form_with model: @friendship, url: '/reject-request', method: :post do |form|%>
              <%= form.hidden_field :friend_id, value: "#{request.id}" %>
              <div>
                <%= form.submit "Reject Request!"%>
              </div>
            <% end %>
        <% end %>
        </li>

      </ul>
    <% end %>

  <% end %>

  
  <article class="timeline">
    <h3>Recent posts:</h3>
    <ul class="posts">
      <%= render @posts %>
    </ul>
  </article>
</section>

Friends
<ul>
  <% @user.friends.each do |friend|%>
    
      <li><%= friend.name %></li>
    
  <% end %>
</ul>